import type { Product, Store } from './types';

export const productsData: Product[] = [
  {
    id: 1,
    name: 'Aquaclair Drinking Water (75cl)',
    description: ['Zero contaminants', 'No after-taste', 'Refreshing'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Aquaclair+Water',
    originalPrice: 150,
    slashedPrice: 130,
    category: 'Beverages',
  },
  {
    id: 2,
    name: 'Reos Anti-Bacterial Handwash (500ml)',
    description: ['Contains glycerine and Aloe', 'Prevents the skin from drying out'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Reos+Handwash',
    originalPrice: 1200,
    slashedPrice: 990,
    category: 'Personal Care',
  },
  {
    id: 3,
    name: 'Myprei Palm Oil (2L)',
    description: ['Suitable for Various Cooking Methods', 'Cholesterol Free'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Myprei+Palm+Oil',
    originalPrice: 6500,
    slashedPrice: 6200,
    category: 'Groceries',
  },
  {
    id: 4,
    name: 'Mealmate Elubo Isu (900g)',
    description: ['100% plant based', 'Free from adulteration', 'Supports weight management'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mealmate+Elubo',
    originalPrice: 4000,
    slashedPrice: 3700,
    category: 'Groceries',
  },
  {
    id: 5,
    name: 'Mealmate Poundo Yam Flour (900g)',
    description: ['100% Plant Based', 'Naturally Wholesome'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mealmate+Poundo',
    originalPrice: 3800,
    slashedPrice: 3500,
    category: 'Groceries',
  },
  {
    id: 6,
    name: 'Gleamly Glow Body Lotion (440ml)',
    description: ['Hydrates deeply and restores', '40ml more care in every bottle'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Gleamly+Lotion',
    originalPrice: 3200,
    slashedPrice: 2900,
    category: 'Personal Care',
  },
  {
    id: 7,
    name: 'Co-Vita Powdered Chocolate Drink (400g)',
    description: ['Vanilla flavoured chocolate drink', 'Contains protein'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Co-Vita+Chocolate',
    originalPrice: 2500,
    slashedPrice: 2390,
    category: 'Beverages',
  },
  {
    id: 8,
    name: 'Reos Toilet Cleaner (800ml)',
    description: ['Removes limescale and rust', 'It lathers better than commercial brands'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Reos+Cleaner',
    originalPrice: 2200,
    slashedPrice: 2000,
    category: 'Household',
  },
  {
    id: 9,
    name: 'Zesty Instant Noodles (Chicken Flavour, 70g)',
    description: ['Quick and delicious', 'Ready in 2 minutes', 'Fortified with vitamins'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Zesty+Noodles',
    originalPrice: 180,
    slashedPrice: 150,
    category: 'Groceries',
  },
  {
    id: 10,
    name: 'Aroma All-Purpose Seasoning (100g)',
    description: ['Enhances any dish', 'Blend of natural spices', 'No MSG added'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Aroma+Seasoning',
    originalPrice: 500,
    slashedPrice: 450,
    category: 'Groceries',
  },
  {
    id: 11,
    name: 'Crunchos Chin Chin (250g)',
    description: ['Classic Nigerian snack', 'Sweet and crunchy', 'Perfect for sharing'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Crunchos+Chin+Chin',
    originalPrice: 800,
    slashedPrice: 720,
    category: 'Snacks',
  },
  {
    id: 12,
    name: 'Sparkle Laundry Detergent (1kg)',
    description: ['Tough on stains', 'Fresh floral scent', 'For top and front loaders'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Sparkle+Detergent',
    originalPrice: 2800,
    slashedPrice: 2550,
    category: 'Household',
  },
  {
    id: 13,
    name: 'Nourish Herbal Soap (150g)',
    description: ['Enriched with Shea Butter', 'Gentle on skin', 'Natural ingredients'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Nourish+Soap',
    originalPrice: 600,
    slashedPrice: 550,
    category: 'Personal Care',
  },
  {
    id: 14,
    name: 'Mama\'s Pride Tomato Paste (400g Tin)',
    description: ['Rich and thick consistency', 'Made from fresh tomatoes', 'Essential for stews'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mama\'s+Pride+Paste',
    originalPrice: 900,
    slashedPrice: 810,
    category: 'Groceries',
  },
  {
    id: 15,
    name: 'Golden Morn Cereal (500g)',
    description: ['Wholesome maize and soya', 'Nutritious family breakfast', 'Just add milk'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Golden+Morn',
    originalPrice: 2000,
    slashedPrice: 1850,
    category: 'Groceries',
  },
  {
    id: 16,
    name: 'Sunola Vegetable Oil (3L)',
    description: ['Cholesterol-free', 'Fortified with Vitamin A', 'Ideal for frying and cooking'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Sunola+Oil',
    originalPrice: 8000,
    slashedPrice: 7600,
    category: 'Groceries',
  },
];

export const storesData: Store[] = [
  { id: 1, name: 'Bokku Mart, Ikeja', address: 'Plot 7 Acme Road, Ikeja, Lagos 101233, NG', hours: '9:00 AM - 6:00 PM', isOpen: true, lat: 6.6213, lng: 3.3367 },
  { id: 2, name: 'Bokku Mart, Victoria Island', address: '123 Adetokunbo Ademola Street, VI, Lagos 101241, NG', hours: '9:00 AM - 8:00 PM', isOpen: true, lat: 6.4284, lng: 3.4218 },
  { id: 3, name: 'Bokku Mart, Lekki', address: 'Block 5, Plot 10, Admiralty Way, Lekki Phase 1, Lagos 105102, NG', hours: '10:00 AM - 9:00 PM', isOpen: true, lat: 6.4473, lng: 3.4723 },
  { id: 4, name: 'Bokku Mart, Surulere', address: '57 Isheri Oshun Road, Surulere, Lagos 102213, NG', hours: '9:00 AM - 6:00 PM', isOpen: false, lat: 6.4984, lng: 3.3444 },
  { id: 5, name: 'Bokku Mart, Yaba', address: '320 Herbert Macaulay Way, Yaba, Lagos 101212, NG', hours: '8:30 AM - 7:00 PM', isOpen: true, lat: 6.5123, lng: 3.3837 },
  { id: 6, name: 'Bokku Mart, Festac', address: '21 Road, Festac Town, Lagos 102312, NG', hours: '9:00 AM - 7:00 PM', isOpen: true, lat: 6.4638, lng: 3.2844 },
];