import type { Product } from './types';

export const productsData: Product[] = [
  {
    id: 1,
    name: 'Aquaclair Drinking Water (75cl)',
    description: ['Zero contaminants', 'No after-taste', 'Refreshing'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Aquaclair+Water',
    originalPrice: 150,
    slashedPrice: 130,
  },
  {
    id: 2,
    name: 'Reos Anti-Bacterial Handwash (500ml)',
    description: ['Contains glycerine and Aloe', 'Prevents the skin from drying out'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Reos+Handwash',
    originalPrice: 1200,
    slashedPrice: 990,
  },
  {
    id: 3,
    name: 'Myprei Palm Oil (2L)',
    description: ['Suitable for Various Cooking Methods', 'Cholesterol Free'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Myprei+Palm+Oil',
    originalPrice: 6500,
    slashedPrice: 6200,
  },
  {
    id: 4,
    name: 'Mealmate Elubo Isu (900g)',
    description: ['100% plant based', 'Free from adulteration', 'Supports weight management'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mealmate+Elubo',
    originalPrice: 4000,
    slashedPrice: 3700,
  },
  {
    id: 5,
    name: 'Mealmate Poundo Yam Flour (900g)',
    description: ['100% Plant Based', 'Naturally Wholesome'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mealmate+Poundo',
    originalPrice: 3800,
    slashedPrice: 3500,
  },
  {
    id: 6,
    name: 'Gleamly Glow Body Lotion (440ml)',
    description: ['Hydrates deeply and restores', '40ml more care in every bottle'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Gleamly+Lotion',
    originalPrice: 3200,
    slashedPrice: 2900,
  },
  {
    id: 7,
    name: 'Co-Vita Powdered Chocolate Drink (400g)',
    description: ['Vanilla flavoured chocolate drink', 'Contains protein'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Co-Vita+Chocolate',
    originalPrice: 2500,
    slashedPrice: 2390,
  },
  {
    id: 8,
    name: 'Reos Toilet Cleaner (800ml)',
    description: ['Removes limescale and rust', 'It lathers better than commercial brands'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Reos+Cleaner',
    originalPrice: 2200,
    slashedPrice: 2000,
  },
  {
    id: 9,
    name: 'Zesty Instant Noodles (Chicken Flavour, 70g)',
    description: ['Quick and delicious', 'Ready in 2 minutes', 'Fortified with vitamins'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Zesty+Noodles',
    originalPrice: 180,
    slashedPrice: 150,
  },
  {
    id: 10,
    name: 'Aroma All-Purpose Seasoning (100g)',
    description: ['Enhances any dish', 'Blend of natural spices', 'No MSG added'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Aroma+Seasoning',
    originalPrice: 500,
    slashedPrice: 450,
  },
  {
    id: 11,
    name: 'Crunchos Chin Chin (250g)',
    description: ['Classic Nigerian snack', 'Sweet and crunchy', 'Perfect for sharing'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Crunchos+Chin+Chin',
    originalPrice: 800,
    slashedPrice: 720,
  },
  {
    id: 12,
    name: 'Sparkle Laundry Detergent (1kg)',
    description: ['Tough on stains', 'Fresh floral scent', 'For top and front loaders'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Sparkle+Detergent',
    originalPrice: 2800,
    slashedPrice: 2550,
  },
  {
    id: 13,
    name: 'Nourish Herbal Soap (150g)',
    description: ['Enriched with Shea Butter', 'Gentle on skin', 'Natural ingredients'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Nourish+Soap',
    originalPrice: 600,
    slashedPrice: 550,
  },
  {
    id: 14,
    name: 'Mama\'s Pride Tomato Paste (400g Tin)',
    description: ['Rich and thick consistency', 'Made from fresh tomatoes', 'Essential for stews'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Mama\'s+Pride+Paste',
    originalPrice: 900,
    slashedPrice: 810,
  },
  {
    id: 15,
    name: 'Golden Morn Cereal (500g)',
    description: ['Wholesome maize and soya', 'Nutritious family breakfast', 'Just add milk'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Golden+Morn',
    originalPrice: 2000,
    slashedPrice: 1850,
  },
  {
    id: 16,
    name: 'Sunola Vegetable Oil (3L)',
    description: ['Cholesterol-free', 'Fortified with Vitamin A', 'Ideal for frying and cooking'],
    imageUrl: 'https://placehold.co/400x400/D1F7F7/002D7A?text=Sunola+Oil',
    originalPrice: 8000,
    slashedPrice: 7600,
  },
];
